### ISSUE TITLE
More NYT API updates

### ISSUE THREAD

**Issue by kgweber-um** [kesyog/crossword#13]
Hi, thanks for all your work on this!

I just pulled this repo today and have been having difficulty getting the endpoints to work...

I've refactored it to call a new `v3` endpoint. If you would like, I can publish my branch for you to review and pull, but I don't want to step on your toes.

As a bonus, I've added a parameter that will pull Mini and/or Bonus puzzles as well :)

LMK if that would be helpful

**Comment by kesyog** [comment]
Hey, I'd love to review your changes. I haven't had a chance to look at #12 because I figured it'd be a good time to step back and refactor things and just haven't had the time to take that on, but it sounds like you've solved that one too. Thanks a lot!

**Comment by kgweber-um** [comment]
Cool! What's the best way to get the changes over to you? I don't have permission to push a branch, but I can fork and push to a repo of my own if you'd prefer to keep this one clean

**Comment by kesyog** [comment]
The easiest way is to make a PR by creating a fork, pushing your branch to your fork, and creating a pull request against this repo. See this GitHub reference: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork.

Ideally, if you have the time and willingness to address any feedback that comes up, we can just go through the PR review process and merge your changes. Otherwise, I can take over and give you credit.

**Comment by kgweber-um** [comment]
Oh for god's sake, I'm commenting in the wrong NYT repo :( Please go ahead and close this.

**Comment by kgweber-um** [comment]
boneheaded mistake :(

**Comment by kesyog** [comment]
Ah darn, no worries. If you're willing to share, I'd still love to learn more about the new API's so that I can incorporate that functionality into this repo when I someday™ find the time and energy.

**Comment by kgweber-um** [comment]
Heh. Good luck with the magical time and energy. I found it for this project while I avoided other stuff I'm supposed to be doing.  I did what I did by listening in on Chrome - there may be much better and more complete approaches.  here's the branch I've set up as a PR for the project I actually am working on:

https://github.com/kgweber-um/nyt-crossword-stats/tree/v3-fix
